POST http://localhost:8000/api/register
Content-Type: 'application/json'

    {
        "name": "Simão Doe",
        "email": "simao@example.com",
        "telephone": "88999999999",
        "type": "driver",
        "password": "12345678"
    }